Обновление (RU) strings.xml
sapphirepro/screenwidget-translations pull request #3
Opened 2018-04-07 09:52 UTC by SHURmanizer

Перепахал и переосмыслил многое, может быть где-то ошибся и загнал себя в ментальный тупик... ;] (ну и еще не уверен про свои добавленные тэги жирности - <b>)

2018-04-07 10:04 UTC, sapphirepro commented
Тут надо подумать. Может создать недопонимания пользователей. Двойное нажатие переключает на следующий элемент в массиве, а не обязательно увеличивает время, как и тройное нажатие не обязательно его уменьшает.

Сортировка используется при создании массива. По умолчанию - элементы выставляются по возрастанию, можно по убыванию или оставить как указал пользователь. Двойной и тройной тап при этом неизменно берут следующий или предыдущий элемент массива соответственно.

2018-04-07 10:29 UTC, sapphirepro requested changes
Тут надо подумать. Может создать недопонимания пользователей. Двойное нажатие переключает на следующий элемент в массиве, а не обязательно увеличивает время, как и тройное нажатие не обязательно его уменьшает.

Сортировка используется при создании массива. По умолчанию - элементы выставляются по возрастанию, можно по убыванию или оставить как указал пользователь. Двойной и тройной тап при этом неизменно берут следующий или предыдущий элемент массива соответственно.

Думаю не стоит полностью переформулировать описание двойного и тройного нажатия, чтобы пользователи не запутались и не закидали меня комментариями об ошибках в программе. И думаю лучше оставить либо кавычки, либо не выделять вовсе внизу.

2018-04-11 15:44 UTC, SHURmanizer commented
Идея с массивами и последовательный (в зависимости от вида сортировки) их перебор - это для рядового пользователя слишком сложно... веет чем-то программистским... ;] Я бы сделал визуальнее попроще: таймауты в виде полосок-элементов, которые можно за уголок перемещать вверх/вниз по списку (сортировать), с переключателями слева (вкл/выкл).

2018-04-15 12:38 UTC, sapphirepro commented
Я думаю можно оставить пока как есть. Тем более большинство скорее всего ею не пользуются

2018-04-17 08:51 UTC, SHURmanizer commented
Согласен, скорее всего не используется такой излишний функционал для гиков... хотя наверно оно имеет право на жизнь...

2018-10-05 01:21 UTC, closed without merging